modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="mekanism_beyond"
    version="1.0.0"
    displayName="Mekanism Beyond"
    authors="kousaba"
    description="SF Addon for Mekanism"

[[mixins]]
config="mekanism_beyond.mixins.json"

[[dependencies.mekanism_beyond]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mekanism_beyond]]
    modId="mekanism"
    type="required"
    versionRange="[10.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.mekanism_beyond]]
    modId="mekanismgenerators"
    type="required"
    versionRange="[10.7.15,)"
    ordering="AFTER"
    side="BOTH"